# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: TMAPool

steps:
- task: FlutterInstall@0
  displayName: 'Install Flutter SDK'
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'latest'

- task: FlutterCommand@0
  displayName: 'Run Flutter Doctor'
  inputs:
    projectDirectory: '.'
    arguments: 'doctor -v'

- task: FlutterCommand@0
  displayName: 'Run Flutter Pub Get'
  inputs:
    projectDirectory: '.'
    arguments: 'pub get'

- task: FlutterBuild@0
  inputs:
    target: 'aab'
    projectDirectory: '.'
    buildNumber: '16052025'
    buildName: '0.0.1'

- task: CopyFiles@2
  inputs:
    contents: '**/app-release.aab'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: Android